version: 2.1
orbs:
  python: circleci/python@1.5.0
  slack: circleci/slack@4.10.1
jobs:
  test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            pip install -r requirements.txt
            pytest
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
  deploy_python_any_where:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
            ssh $PYTHON_ANY_WHERE_USER@$PYTHON_ANY_WHERE_HOST "cd flask_app_for_test_circleCI; source venv/bin/activate; python3 deployment.py; ./reload.sh";
  deploy_ec2:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
            ssh $EC2_USER@$EC2_HOST "cd flask_app_for_test_circleCI; source venv/bin/activate; python3 deployment.py";

workflows:
  version: 2
  deploy-and-test:
    jobs:
      - test:
          context: slack-secrets
          filters:
            tags:
              only:
                - /^[0-9a-zA-Z]+.ci-prod/
            branches:
              ignore: /.*/  
      - deploy_python_any_where:
          context: slack-secrets
          requires:
            - test
          filters:
            tags:
              only: 
                - /^[0-9a-zA-Z]+.ci-prod/
            branches:
              ignore: /.*/
      - deploy_ec2:
          context: slack-secrets
          requires:
            - deploy_python_any_where
          filters:
            tags:
              only: 
                - /^[0-9a-zA-Z]+.ci-prod/
            branches:
              ignore: /.*/
  test_merge:
    jobs:
      - test:
          context: slack-secrets
          filters:
            branches:
              only:
                - main