name: Trigger Build on Push

on:
  pull_request:
    types: [open, synchronize]

jobs:
  trigger-build:
    if: ${{ (github.event.issue.pull_request && contains( github.event.comment.body, 'trigger.CI' ))  }} 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
