name: Trigger Build on PR

on:
  pull_request:
    types: [opened, reopened, syncronize]
on:
  push:
    branches:
      - main

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
